// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor).
import type { MapSource } from "../types.ts";

export const ARENA: MapSource = {
  id: "arena",
  name: "Arena",
  width: 800,
  height: 600,
  walls: [
    { x: 0, y: 0, width: 800, height: 40 },
    { x: 0, y: 40, width: 40, height: 560 },
    { x: 360, y: 40, width: 80, height: 80 },
    { x: 760, y: 40, width: 40, height: 560 },
    { x: 120, y: 120, width: 80, height: 80 },
    { x: 600, y: 120, width: 80, height: 80 },
    { x: 360, y: 160, width: 80, height: 80 },
    { x: 280, y: 240, width: 40, height: 120 },
    { x: 480, y: 240, width: 40, height: 120 },
    { x: 40, y: 280, width: 40, height: 40 },
    { x: 720, y: 280, width: 40, height: 40 },
    { x: 360, y: 360, width: 80, height: 80 },
    { x: 120, y: 400, width: 80, height: 80 },
    { x: 600, y: 400, width: 80, height: 80 },
    { x: 360, y: 480, width: 80, height: 120 },
    { x: 40, y: 560, width: 320, height: 40 },
    { x: 440, y: 560, width: 320, height: 40 },
  ],
  spawns: [
    { x: 60, y: 60 },
    { x: 740, y: 540 },
    { x: 740, y: 60 },
    { x: 60, y: 540 },
  ],
};
