// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor). Do not edit by hand.
import type { MapSource } from "../types.ts";
import { ARENA } from "./arena.ts";
import { PLAZA } from "./plaza.ts";

export const MAP_SOURCES: MapSource[] = [ARENA, PLAZA];
