// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor). Do not edit by hand.
import type { MapSource } from "../types.ts";
import { CROSSROADS } from "./crossroads.ts";
import { LABYRINTH } from "./labyrinth.ts";
import { WARREN } from "./warren.ts";

export const MAP_SOURCES: MapSource[] = [CROSSROADS, LABYRINTH, WARREN];
