// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor).
import type { MapSource } from "../types.ts";

export const NEW_MAP: MapSource = {
  id: "new-map",
  name: "Test",
  tileSize: 64,
  wallThickness: 4,
  layout: [
    "+-+-+-+-+-+-+-+-+-+-+-+-+",
    "|1                     3|",
    "+ + + + + + + + + + + + +",
    "|         | |           |",
    "+ + + + +-+ +-+ + + + + +",
    "|                       |",
    "+ + + + +-+ +-+ + + + + +",
    "|         | |           |",
    "+ + + + + + + + + + + + +",
    "|                       |",
    "+ + + + +-+ +-+ + + + + +",
    "|       |     |         |",
    "+ + + + +-+ +-+ + + + + +",
    "|         | |           |",
    "+ + + + + + + + + + + + +",
    "|         | |           |",
    "+ + + + + + + + + + + + +",
    "|4                     2|",
    "+-+-+-+-+-+-+-+-+-+-+-+-+",
  ],
};
