// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor).
import type { MapSource } from "../types.ts";

export const PLAZA: MapSource = {
  id: "plaza",
  name: "Plaza",
  width: 800,
  height: 600,
  walls: [
    { x: 0, y: 0, width: 800, height: 40 },
    { x: 0, y: 40, width: 40, height: 560 },
    { x: 760, y: 40, width: 40, height: 560 },
    { x: 360, y: 240, width: 80, height: 120 },
    { x: 40, y: 560, width: 720, height: 40 },
  ],
  spawns: [
    { x: 60, y: 60 },
    { x: 740, y: 540 },
    { x: 740, y: 60 },
    { x: 60, y: 540 },
  ],
};
