import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Plugin } from "vite";
// Relative import (not the package name) so Vite bundles it into the config
// instead of handing the workspace package's .ts sources to Node at runtime.
import { MAP_ID_PATTERN, validateMapSource, type MapSource } from "../../../packages/shared/src/maps/types.ts";

/**
 * Dev-server-only endpoints used by the map editor (`/?editor`) to persist maps
 * as TypeScript source under packages/shared/src/maps/data:
 *
 *   PUT    /__editor/maps/:id   body: MapSource JSON  -> writes data/<id>.ts, regenerates data/index.ts
 *   DELETE /__editor/maps/:id                          -> removes data/<id>.ts, regenerates data/index.ts
 *
 * Never active in `vite build`, so production bundles contain no trace of it.
 */
export function mapEditorPlugin(): Plugin {
  const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
  const dataDir = path.join(repoRoot, "packages/shared/src/maps/data/");
  const prefix = "/__editor/maps/";

  return {
    name: "tank-arena:map-editor",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url ?? "";
        if (!url.startsWith(prefix)) return next();
        const id = decodeURIComponent(url.slice(prefix.length).split("?")[0]!);
        handle(req, res, id, dataDir, repoRoot).catch((err: unknown) => {
          const message = err instanceof Error ? err.message : String(err);
          send(res, 500, { error: message });
        });
      });
    },
  };
}

async function handle(
  req: IncomingMessage,
  res: ServerResponse,
  id: string,
  dataDir: string,
  repoRoot: string,
): Promise<void> {
  if (!MAP_ID_PATTERN.test(id)) {
    return send(res, 400, { error: `invalid map id "${id}"` });
  }
  const file = path.join(dataDir, `${id}.ts`);

  if (req.method === "PUT") {
    const body = await readJson(req);
    if (!isMapSource(body) || body.id !== id) {
      return send(res, 400, { error: "body must be a MapSource whose id matches the URL" });
    }
    const errors = validateMapSource(body);
    if (errors.length > 0) return send(res, 400, { error: errors.join("; ") });

    await mkdir(dataDir, { recursive: true });
    await writeFile(file, emitMapModule(body));
    await writeIndex(dataDir);
    return send(res, 200, { ok: true, file: path.relative(repoRoot, file) });
  }

  if (req.method === "DELETE") {
    const ids = await listIds(dataDir);
    if (!ids.includes(id)) return send(res, 404, { error: `map "${id}" not found` });
    if (ids.length === 1) return send(res, 400, { error: "cannot delete the last map" });
    await rm(file);
    await writeIndex(dataDir);
    return send(res, 200, { ok: true });
  }

  send(res, 405, { error: "method not allowed" });
}

async function listIds(dataDir: string): Promise<string[]> {
  const entries = await readdir(dataDir);
  return entries
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .map((f) => f.slice(0, -3))
    .filter((id) => MAP_ID_PATTERN.test(id))
    .sort();
}

async function writeIndex(dataDir: string): Promise<void> {
  const ids = await listIds(dataDir);
  const imports = ids.map((id) => `import { ${constName(id)} } from "./${id}.ts";`).join("\n");
  const list = ids.map(constName).join(", ");
  const src = `// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor). Do not edit by hand.
import type { MapSource } from "../types.ts";
${imports}

export const MAP_SOURCES: MapSource[] = [${list}];
`;
  await writeFile(path.join(dataDir, "index.ts"), src);
}

export function emitMapModule(map: MapSource): string {
  const walls = map.walls
    .map((w) => `    { x: ${num(w.x)}, y: ${num(w.y)}, width: ${num(w.width)}, height: ${num(w.height)} },`)
    .join("\n");
  const spawns = map.spawns
    .map((s) => {
      const angle = s.angle === undefined ? "" : `, angle: ${num(s.angle)}`;
      return `    { x: ${num(s.x)}, y: ${num(s.y)}${angle} },`;
    })
    .join("\n");
  return `// Generated by the map editor (pnpm dev, then http://localhost:3000/?editor).
import type { MapSource } from "../types.ts";

export const ${constName(map.id)}: MapSource = {
  id: ${JSON.stringify(map.id)},
  name: ${JSON.stringify(map.name)},
  width: ${num(map.width)},
  height: ${num(map.height)},
  walls: [
${walls}
  ],
  spawns: [
${spawns}
  ],
};
`;
}

function constName(id: string): string {
  return id.replace(/-/g, "_").toUpperCase();
}

function num(n: number): string {
  return String(Math.round(n * 1000) / 1000);
}

function isMapSource(v: unknown): v is MapSource {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.id === "string" &&
    typeof o.name === "string" &&
    typeof o.width === "number" &&
    typeof o.height === "number" &&
    Array.isArray(o.walls) &&
    o.walls.every(isRect) &&
    Array.isArray(o.spawns) &&
    o.spawns.every(isSpawn)
  );
}

function isRect(v: unknown): boolean {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.x === "number" && typeof o.y === "number" && typeof o.width === "number" && typeof o.height === "number"
  );
}

function isSpawn(v: unknown): boolean {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return typeof o.x === "number" && typeof o.y === "number" && (o.angle === undefined || typeof o.angle === "number");
}

async function readJson(req: IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(Buffer.from(chunk));
  const text = Buffer.concat(chunks).toString("utf8");
  if (text.length > 1_000_000) throw new Error("body too large");
  return JSON.parse(text);
}

function send(res: ServerResponse, status: number, body: unknown): void {
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify(body));
}
